### ISSUE TITLE
Gå igenom font storlekar.

### ISSUE THREAD

**Issue by noahlissner** [noahlissner/js-inl2-webbshop#18]
Vi måste gå igenom alla font-storlekar! vissa blir för waaay för stora med clamp.

**Comment by dennislundgren** [comment]
I'll take this one now. They are now optimized towards one clamp. I'll create a different clamp for each one though with the same minimum size.

**Comment by dennislundgren** [comment]
Font-sizes have been updated. Looks better now. 

Close issue if all agree.
